### PR TITLE
Unit test errors on Windows due to files being left open

### LINKED ISSUE #177: testIterator test from QueueFileTest file is not passing ?
I downloaded the code a week ago and I was wondering if someone else has seeing testIterator test fail on every run.

// Expected behavior
The loop should cycle 2 times leaving variable saw with a value of 2

// Actual behavior
Variable saw has a value of 3 when 2 is expected
java.lang.AssertionError: Not true that <3> is equal to <2>

### PR DESCRIPTION
**Pull request by chrissmith-mcafee**
Added close calls to tests where files were being left open. This resulted in test case errors on Windows when files were deleted in cleanup (Did not occur on Linux).

Closes #177.

### CODE REVIEW

**Comment by chrissmith-mcafee** [comment]
Interesting, running check locally didn't show any issues, I will look into those check related errors.

**Comment by JakeWharton** [comment]
Are you running `./gradlew build` (or `check`)? Looks like your code style settings differ in where they place whitespcae.

**Comment by chrissmith-mcafee** [comment]
Sorry about that. IDE appears to have applied our local styling on the commit (after we ran the check locally).

File: tape/src/test/java/com/squareup/tape2/QueueFileLoadingTest.java [hunk 1]
```diff
@@ -33,20 +33,32 @@
     assertTrue(testFile.delete());
     assertFalse(testFile.exists());
     QueueFile queue = new QueueFile.Builder(testFile).build();
-    assertEquals(0, queue.size());
-    assertTrue(testFile.exists());
+    try {
+      assertEquals(0, queue.size());
+      assertTrue(testFile.exists());
+    } finally {
+      queue.close();
```
Comment (NightlyNexus) [inline tape/src/test/java/com/squareup/tape2/QueueFileLoadingTest.java]: do most of these need the try-finally blocks (instead of only closing afterwards)? if there's an exception in these tests, does it matter if the file is closed?

Comment (chrissmith-mcafee) [reply tape/src/test/java/com/squareup/tape2/QueueFileLoadingTest.java]: The problem is on Windows, the file won't be deleted if an exception occurs.

Comment (chrissmith-mcafee) [reply tape/src/test/java/com/squareup/tape2/QueueFileLoadingTest.java]: Meaning they won't be cleaned up after the test. If that isn't a concern, I can remove the try-finally.

Comment (NightlyNexus) [reply tape/src/test/java/com/squareup/tape2/QueueFileLoadingTest.java]: oh, for my own understanding, do you mean that the `cleanup()` that deletes the file will fail if this isn't closed? if so, why is that?

Comment (chrissmith-mcafee) [reply tape/src/test/java/com/squareup/tape2/QueueFileLoadingTest.java]: Yes, it fails because the file still has an open handle. Windows reports the file as being open which causes the delete to fail (Linux does not prevent deletion).

Comment (NightlyNexus) [reply tape/src/test/java/com/squareup/tape2/QueueFileLoadingTest.java]: Oh, that's interesting. Thanks for explaining it to me!

Comment (NightlyNexus) [reply tape/src/test/java/com/squareup/tape2/QueueFileLoadingTest.java]: i guess the close could in `cleanup()`? dunno which is preferable.

Comment (chrissmith-mcafee) [reply tape/src/test/java/com/squareup/tape2/QueueFileLoadingTest.java]: That would work if QueueFile became a class member. It would still require explicit closing for cases that utilize multiple queues (QueueFileTest.testIterator, QueueTestFile.testAddAndRemoveElements, etc.).

Not sure the preference at this point. Maybe the easiest thing to do would just be to add the close() calls on those particular cases where it was failing on Windows. The try-finally could be removed as it isn't being applied on all cases consistently. Thus, there would be only be minor changes. At some point in the future a refactor could be done (try-with-resource might make the most sense).

**Comment by JakeWharton** [comment]
Maybe we should be using try-with-resources for the tests? My only worry is that the current solution is really easy to regress.

**Comment by chrissmith-mcafee** [comment]
I went ahead and made the minimum changes required for the tests to pass on Windows.
