### PR TITLE
Drop unchecked FileException for raw IOException.

### LINKED ISSUE #35: FileException shouldn't be unchecked
In various places an IOException is promoted to a FileException.  This means that when there's an issue in the underlying file for whatever reason, tape will throw an unchecked exception.  Unless the caller is careful to remember to wrap a try/catch around calls into tape functions, tape may unexpectedly kill the app.

(While it's true that there's little tape can do to recover from IOExceptions, it'd be nice to encourage the app to decide how to recover from these "unrecoverable" sorts of errors -- for example, the app could inform the user that it just lost some of their data but is attempting to recover.  When the alternative is just to crash, that doesn't seem so bad.)

PS: I'm relatively new to Java, so feel free to just close this if I'm reopening some age-old debate that you've already decided upon.  But it seems at least "Effective Java" says that runtime exceptions should only be used for programming errors.

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #35. Closes #36.

### CODE REVIEW

**Comment by f2prateek** [comment]
LGTM

File: tape/src/main/java/com/squareup/tape/FileObjectQueue.java [hunk 1]
```diff
@@ -39,75 +33,59 @@ public FileObjectQueue(File file, Converter<T> converter) throws IOException {
     this.queueFile = new QueueFile(file);
   }
 
+  public File file() {
```
Comment (f2prateek) [inline tape/src/main/java/com/squareup/tape/FileObjectQueue.java]: What's this added for?

Comment (JakeWharton) [inline tape/src/main/java/com/squareup/tape/FileObjectQueue.java]: `FileException` exposed the underlying `File`. This allows calling code to retrieve the `File` for exception reporting purposes.
